/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyFirstComponent {
    'name': string;
  }
}

declare namespace LocalJSX {
  interface MyFirstComponent extends JSXBase.HTMLAttributes {
    'name'?: string;
  }

  interface IntrinsicElements {
    'my-first-component': MyFirstComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLMyFirstComponentElement extends Components.MyFirstComponent, HTMLStencilElement {}
  var HTMLMyFirstComponentElement: {
    prototype: HTMLMyFirstComponentElement;
    new (): HTMLMyFirstComponentElement;
  };

  interface HTMLElementTagNameMap {
    'my-first-component': HTMLMyFirstComponentElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

