/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CalciteSelect {
    'options': any;
  }
  interface CalciteSelectVariant {}
  interface MyFirstComponent {
    'name': string;
  }
}

declare namespace LocalJSX {
  interface CalciteSelect extends JSXBase.HTMLAttributes {
    'options'?: any;
  }
  interface CalciteSelectVariant extends JSXBase.HTMLAttributes {}
  interface MyFirstComponent extends JSXBase.HTMLAttributes {
    'name'?: string;
  }

  interface IntrinsicElements {
    'calcite-select': CalciteSelect;
    'calcite-select-variant': CalciteSelectVariant;
    'my-first-component': MyFirstComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLCalciteSelectElement extends Components.CalciteSelect, HTMLStencilElement {}
  var HTMLCalciteSelectElement: {
    prototype: HTMLCalciteSelectElement;
    new (): HTMLCalciteSelectElement;
  };

  interface HTMLCalciteSelectVariantElement extends Components.CalciteSelectVariant, HTMLStencilElement {}
  var HTMLCalciteSelectVariantElement: {
    prototype: HTMLCalciteSelectVariantElement;
    new (): HTMLCalciteSelectVariantElement;
  };

  interface HTMLMyFirstComponentElement extends Components.MyFirstComponent, HTMLStencilElement {}
  var HTMLMyFirstComponentElement: {
    prototype: HTMLMyFirstComponentElement;
    new (): HTMLMyFirstComponentElement;
  };

  interface HTMLElementTagNameMap {
    'calcite-select': HTMLCalciteSelectElement;
    'calcite-select-variant': HTMLCalciteSelectVariantElement;
    'my-first-component': HTMLMyFirstComponentElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

